name: Publish docker image to Github packages

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version tag (e.g., v1.2.3)"
        required: true
        default: "v0.0.0"
        type: string

permissions:
  contents: write
  packages: write

jobs:
  push-to-packages:
    name: Push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/golem-base/spoditor:${{ steps.tag.outputs.tag }}

  create-release:
    name: Create release and generate bundle yaml
    runs-on: ubuntu-latest
    needs: push-to-packages
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Set tag
        id: tag
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "tag=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - name: Generate bundle YAML
        run: IMG="ghcr.io/golem-base/spoditor:${{ steps.tag.outputs.tag }}" make build-yaml

      - name: Create GitHub Release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2.2.2
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          files: bundle.yaml
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add to Existing Release
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v2.2.2
        with:
          files: bundle.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
